trigger:
  - main

pool:
  name: "MyLocalPool"
  demands:
    - agent.name -equals DINODAN

variables:
  - group: "API-Secrets"
  - name: buildConfiguration
    value: "Release"
  - name: dockerRegistryServiceConnection
    value: "DockerHub-Conn"
  - name: imageRepository
    value: "danieleduardoperez/product-api"
  - name: tag
    value: "$(Build.BuildId)"

stages:
  - stage: BuildAndTest
    displayName: "Build and Test Stage"
    jobs:
      - job: Build
        displayName: "Build and Unit Tests"
        steps:
          - task: UseDotNet@2
            displayName: "Use .NET 9 SDK"
            inputs:
              packageType: "sdk"
              version: "9.x"

          - task: DotNetCoreCLI@2
            displayName: "Restore Dependencies"
            inputs:
              command: "restore"
              projects: "**/*.csproj"

          - task: DotNetCoreCLI@2
            displayName: "Run Unit Tests"
            inputs:
              command: "test"
              projects: "**/*Tests/*.csproj"
              arguments: "--configuration $(buildConfiguration) --logger trx"
              publishTestResults: true

          - task: Docker@2
            displayName: "Build and Push Docker Image"
            inputs:
              command: "buildAndPush"
              repository: $(imageRepository)
              dockerfile: "**/Dockerfile"
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

  - stage: Deploy
    displayName: "Deploy to Azure"
    dependsOn: BuildAndTest
    condition: succeeded()
    jobs:
      - job: DeployToContainerApp
        displayName: "Deploy to Azure Container Apps"
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy to Container App via CLI'
            inputs:
              azureSubscription: 'Azure-Service-Conn'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Capturamos la variable de conexión de Neon de forma segura
                $DB_CONN = "$(Prod_Db_Connection)"
                
                # Ejecutamos el deploy inyectando cada variable como un argumento independiente protegido por comillas
                az containerapp up `
                  --name products-api `
                  --resource-group rg-products-prod `
                  --environment env-products-prod `
                  --image danieleduardoperez/product-api:latest `
                  --set-env-vars "AzureAd__ClientId=bcb4359b-87c5-470f-b900-edfdd67b1574" "AzureAd__TenantId=f502be2a-1ca4-44ab-bb4b-408bc89ebcc0" "ConnectionStrings__DefaultConnection=$DB_CONN"
